[tox]
envlist = linter, py311
#envlist = py311
isolated_build = True

[testenv]
setenv =
        PATH = {env:HOME}/.pyenv/shims:{env:PATH}
        PIP_CERT = /etc/pki/tls/certs/hlca.pem
        REQUESTS_CA_BUNDLE = /etc/pki/tls/certs/hlca.pem
        PIP_EXTRA_INDEX_URL = https://pypi.int.hopliteindustries.com/root/pypi
        PIP_INDEX_URL = https://pypi.int.hopliteindustries.com/hoplite/prod
changedir = tests
deps = pytest
commands =
        pytest --basetemp="{envtmpdir}" -random-order  {posargs}
recreate = true

[testenv:linter]
changedir = .
allowlist_externals =
        ruff
        ty
commands =
        ruff format --check libnrdpd
        ruff check libnrdpd

[testenv:docs]
changedir = .
whitelist_externals = make
deps = sphinx
        sphinx-autodoc-typehints

commands = sphinx-build -M html "doc-src" "doc-out"

